### PR TITLE
Getters for underlying libraries and setters for data fields

### LINKED ISSUE #13: Make QR code builder accessible via getter

### PR DESCRIPTION
**Pull request by tormit**
Constants and setters for data fields based on specification https://qr-platba.cz/pro-vyvojare/specifikace-formatu/.
Basic data sanitation.
Getters for underlying Spayd and QR code builder to be able to modify certain elements.

### CODE REVIEW

**Comment by petrknap** [comment]
Thanks for contribution, I will look at it soon. :)

**Comment by petrknap** [comment]
How much of a rush are you in? It's going to need unit tests at the very least, and looking at the whole thing, I'd probably refactor it. If you are in a hurry I'd release it when the tests are added, if you're not in a hurry I'll refactor it first.

**Comment by tormit** [comment]
I could add some tests. What would you refactor? Please don't break my code :)

**Comment by petrknap** [comment]
I did just small refactoring for current version, but I'm working on big refactor which I will release as major update. Add test for the `sanitizeString` method as it is modifying input data then I will release it as last update of current version. In next version I will replace it by `SpaydValue` object.

**Comment by tormit** [comment]
I moved the sanitation to new utility class to test it easily and make main class cleaner.
Also added the tests. Not much to test though.

**Comment by tormit** [comment]
Also I would suggest to improve the sanitation by transliterating non ISO-8859-1 symbols and striping special characters.
On my implementation level, I use voku UTF8 library for that. Here's example:

```php
private function sanitize(string $value)
    {
        return \voku\helper\UTF8::to_filename(mb_strtoupper(\voku\helper\UTF8::to_ascii($value), 'UTF-8'), false, ' ');
    }
```

Not sure you if you like additional dependencies in your project.
I, however, would gladly move this also down to your package level.

**Comment by petrknap** [comment]
I created a new branch for v3, so if you wish, you can add it there. I will release it as next v3 release (if it will be backward compatible) and refactor it to v4 (if it will make sense).

**Comment by petrknap** [comment]
```
FILE: /app/src/Util.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 17 | ERROR | [x] Expected 1 newline at end of file; 0 found
----------------------------------------------------------------------
```

**Comment by petrknap** [comment]
Note me here when it will be ready and I will look at it once again and merge it. :)

**Comment by tormit** [comment]
I think let's leave the improved sanitation to v4. Adding additional library could cause version conflicts for someone.

**Comment by petrknap** [comment]
So is this ready to review/merge? :)

BTW I don't think that changing requirements is an issue - these who will have conflict will be able to install previous version (and also following version in this case).

**Comment by tormit** [comment]
I think you can merge. I don't have time before next week to deal with this.

**Review by petrknap — APPROVED** [review]

**Pull request merged**
